name: luvasi
description: "A new Flutter project."
publish_to: 'none' # Remove a this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.10.0
  firebase_auth: ^4.8.0
  qr_flutter: ^4.0.0
  cloud_functions: ^4.0.5
  cloud_firestore: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
